; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = upesy_wroom

[env:upesy_wroom]
platform = espressif32
board = denky32
framework = arduino
lib_deps =
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/DHT sensor library@^1.4.7
	links2004/WebSockets@^2.4.0
	tobiasschuerg/ESP8266 Influxdb@^3.13.2
	adafruit/Adafruit MAX31865 library@^1.6.2
	dlloydev/QuickPID@^3.1.9
	tyhenry/CheapStepper@^0.2.1
	knolleary/PubSubClient@^2.8
	adafruit/Adafruit INA219@^1.2.1
	bblanchon/ArduinoJson@^7.0.0
monitor_speed = 115200
build_flags =
	-Wno-parentheses
	-DDEFAULT_CEILING_SP_F=160.0f
	-DDEFAULT_BENCH_SP_F=120.0f
	-DFIRMWARE_VERSION=\"1.0.0\"
board_build.filesystem = littlefs
board_build.filesystem_data_dir = data
board_build.partitions = partitions_ota.csv
targets = upload, uploadfs
extra_scripts = scripts/upload_fs.py

[env:native]
platform = native
build_flags = -std=c++14
test_build_src = false
test_framework = unity
